http:
  bind: 0.0.0.0:8080
  log_timestamp: true

subscribe_timeout: 5

units:
  - name: rsyslog.service
    on_active:
      - logger "{unit_name} {unit_state}"
    on_inactive:
      - logger "{unit_name} {unit_state}"
    on_failed:
      - logger "{unit_name} {unit_state}"
    blocked_by:
      - crond.service
