http:
  # bind http server to this address:port
  bind: 0.0.0.0:8080
  # add timestamp to log?
  log_timestamp: true
  # X-Token header
  x_token: ""

# receive all changed units every interval over dbus
subscribe_interval: 5

# units list
units:
  - name: rsyslog.service
    on_active:
      - logger "{unit_name} {unit_state}"
    on_inactive:
      - logger "{unit_name} {unit_state}"
    on_failed:
      - logger "{unit_name} {unit_state}"
    blocked_by:
      - crond.service
