http:
  bind: 0.0.0.0:8080

subscribe_timeout: 5

units:
  - name: rsyslog.service
    on_active:
      - logger "test1.service active"
    on_inactive:
      - logger "test1.service inactive"
    on_failed:
      - logger "test1.service failed"
    blocked_by:
      - test2.service

  - name: test2.service
    on_active:
      - logger "test1.service active"
    on_failed:
      - logger "test2.service.failed"
